console.log("Operadores Aritmeticos");
numero1=20;
numero2=5;
console.log("suma");
suma=numero1+numero2;
console.log("Resultado",suma);
console.log("resta");
resta=numero1-numero2;
console.log("Resultado",resta);
console.log("multipliacion");
multiplicacion=numero1*numero2;
console.log("Resultado",multiplicacion);
console.log("division");
division=numero1/numero2;
console.log("Resultado",division);
console.log("modulo");
modulo=numero1%numero2;
console.log("Resultado",modulo);
console.log("potencia");
potencia=numero1**numero2;
console.log("Resultado",potencia);

console.log("Operadores de Comparacion");
console.log("Igualdad debil ==", "4"==4);
console.log("Igualdad estricta ===", "4"===4);
console.log("Desigualdad debil !=", "4"!=4);
console.log("Desigualdad estricta !==", "4"!==4);
console.log("Mayor que >", "4">4);
console.log("Menor que <", "4"<4);
console.log("Mayor o igual >=", "4">=4);
console.log("Menor o igual <=", "4"<=4);

console.log("Operadores Logicos");
console.log("y And &&", "3" <=3 && "3" >=3);
console.log("o OR && ||", "2" <=2 || "3" >=1);
console.log("Negacion !", !(2==2));